import os
import sys
import platform

Import("env")

main_sources = [
	'actionevent.cpp',
	'basiccontainer.cpp',
	'cliprectangle.cpp',
	'color.cpp',
	'defaultfont.cpp',
	'event.cpp',
	'exception.cpp',
	'focushandler.cpp',
	'font.cpp',
	'graphics.cpp',
	'gui.cpp',
	'guichan.cpp',
	'image.cpp',
	'imagefont.cpp',
	'inputevent.cpp',
	'key.cpp',
	'keyevent.cpp',
	'keyinput.cpp',
	'mouseevent.cpp',
	'mouseinput.cpp',
	'rectangle.cpp',
	'widget.cpp'
]

widget_sources = [
	'widgets/button.cpp',
	'widgets/checkbox.cpp',
	'widgets/container.cpp',
	'widgets/dropdown.cpp',
	'widgets/icon.cpp',
	'widgets/label.cpp',
	'widgets/listbox.cpp',
	'widgets/radiobutton.cpp',
	'widgets/scrollarea.cpp',
	'widgets/slider.cpp',
	'widgets/textbox.cpp',
	'widgets/textfield.cpp',
	'widgets/window.cpp',
]

sdl_sources = [
	'sdl/sdl.cpp',
	'sdl/sdlgraphics.cpp',
	'sdl/sdlimage.cpp',
	'sdl/sdlimageloader.cpp',
	'sdl/sdlinput.cpp'
]


program_sources = [
	main_sources +
	widget_sources +
	sdl_sources
]

guikun = env.Clone()
guikun.ParseConfig('pkg-config --cflags --libs sdl2')
guikun.ParseConfig('pkg-config --cflags --libs SDL2_image')
#TODO : if GL, guikun.Append(LIBS = ['-lGL', '-lGLU'])
guikun.StaticLibrary(target = 'guikun', source = program_sources)

Export('guikun')
